// <auto-generated />
using System;
using DevIt.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevIt.Persistence.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230901141548_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("com.b_velop.DevIt.Domain.Eintrag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Abrechenbar")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("Datum")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExterneId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<double>("Stunden")
                        .HasColumnType("float");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("ExterneId")
                        .IsUnique()
                        .HasFilter("[ExterneId] IS NOT NULL");

                    b.ToTable("Eintraege");
                });

            modelBuilder.Entity("com.b_velop.DevIt.Domain.Pbi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("ProjektId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjektId");

                    b.ToTable("Pbis");
                });

            modelBuilder.Entity("com.b_velop.DevIt.Domain.Projekt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExterneId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("ExterneId")
                        .IsUnique()
                        .HasFilter("[ExterneId] IS NOT NULL");

                    b.ToTable("Projekte");
                });

            modelBuilder.Entity("com.b_velop.DevIt.Domain.Pbi", b =>
                {
                    b.HasOne("com.b_velop.DevIt.Domain.Projekt", null)
                        .WithMany("Pbis")
                        .HasForeignKey("ProjektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("com.b_velop.DevIt.Domain.Projekt", b =>
                {
                    b.Navigation("Pbis");
                });
#pragma warning restore 612, 618
        }
    }
}
