name: Docker Image devit-api identity-servus

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}
    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"
    - uses: docker/login-action@v2.1.0
      name: Docker Login
      with:
        username: millegalb
        password: ${{secrets.DOCKER_HUB_PW}}
    - uses: actions/checkout@v3
    #- name: Build DevIt Service
    #  run: docker build ./dotnet --file ./DevIt.Service/Dockerfile --tag millegalb/devit-service:0.0.$BUILD_NUMBER
    - name: Build Dude BFF
      run: docker build ./dotnet --file ./Dude.Bff/Dockerfile --tag millegalb/dude-bff:0.0.$BUILD_NUMBER
    - name: Build Identity Cat
      run: docker build ./dotnet --file ./IdentityCat.Service/Dockerfile --tag millegalb/identity-cat:0.0.$BUILD_NUMBER
    - name: Build Mqtt Service
      run: docker build ./dotnet --file ./Mqtt.Service/Dockerfile --tag millegalb/mqtt-service:0.0.$BUILD_NUMBER
    - name: Push the Docker image Idenetity
      run: docker push millegalb/identity-cat:0.0.$BUILD_NUMBER
    - name: Push the Docker image DevIt
      run: docker push millegalb/devit-service:0.0.$BUILD_NUMBER
    - name: Push the Docker image Dude Bff
      run: docker push millegalb/dude-bff:0.0.$BUILD_NUMBER
    - name: Push the Docker image Mqtt Service
      run: docker push millegalb/mqtt-service:0.0.$BUILD_NUMBER
