name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm i
      run: npm i

    - name: Nrwl Nx
      # You may pin to the exact commit or the version.
      # uses: MansaGroup/nrwl-nx-action@a531870269e0c1eeb7af6247c4a206c31cae82cc
      uses: MansaGroup/nrwl-nx-action@v3
      with:
        # Comma-separated list of targets to execute
        targets: lint,build,deploy
        # Comma-separated list of projects to use
        projects: pbi-o-mat,stunden
        # Run the targets on all projects
        all: false
        workingDirectory: .


