name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup pnpm
      # You may pin to the exact commit or the version.
      # uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd
      uses: pnpm/action-setup@v2.2.4
      with:
        version: "7.21.0"
        run_install: true
    - name: Nrwl Nx
      # You may pin to the exact commit or the version.
      # uses: MansaGroup/nrwl-nx-action@a531870269e0c1eeb7af6247c4a206c31cae82cc
      uses: MansaGroup/nrwl-nx-action@v3
      with:
        # Comma-separated list of targets to execute
        targets: lint,build
        # Comma-separated list of projects to use
        projects: pbi-o-mat,stunden
        # Run the targets on all projects
        all: false
        workingDirectory: .
    
    - name: S3 Sync Stunden
      # You may pin to the exact commit or the version.
      # uses: jakejarvis/s3-sync-action@be0c4ab89158cac4278689ebedd8407dd5f35a83
      uses: jakejarvis/s3-sync-action@v0.5.1
      env:
        AWS_REGION: 'European Union (Germany)'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_ENDPOINT: 'https://eu2.contabostorage.com'
        SOURCE_DIR: 'dist/apps/stunden'
        
    - name: S3 Sync pbi-o-mat
      # You may pin to the exact commit or the version.
      # uses: jakejarvis/s3-sync-action@be0c4ab89158cac4278689ebedd8407dd5f35a83
      uses: jakejarvis/s3-sync-action@v0.5.1
      env:
        AWS_REGION: 'European Union (Germany)'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKE_PBI_O_MAT }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_ENDPOINT: 'https://eu2.contabostorage.com'
        SOURCE_DIR: 'dist/apps/pbi-o-mat'
